[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 900
  startPeriodSeconds = 30
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
